# Astroinformática I - Aula 03

## Assuntos cobertos: 

### Manipulação de vetores, matrizes e introdução ao módulo numpy

## Vetores (ou Listas)

In [ ]:
languages=["Python", "C","C++", "Java","Perl"]
print(languages[0]+" and "+languages[1]+" are quite different!")
print("Acessing the last element of the list: "+languages[-1])
print(len(languages))

## Exercício I

In [ ]:
A = [1,2,3,4,5]
B = [6,7,8,9,10]

produto = 0

for i in range (len(A)):
    produto += A[i] * B[i]
print(produto)

In [ ]:
A = [1,2,3,4,5]
B = [6,7,8,9,10]

p=A[0]*B[0]+A[1]*B[1]+A[2]*B[2]+A[3]*B[3]+A[4]*B[4]
print(p)

## Vetores em Numpy

In [45]:
import numpy as np
x=np.array([42,47,11])
print(x)

[42 47 11]


## Exercício II

In [48]:
P = np.dot(np.array(A),np.array(B))
print(P)

130


In [42]:
import numpy as np
A = [1,2,3,4,5]
B = [6,7,8,9,10]

produto = np.dot(A,B)

print(produto)

## Exercício III

In [50]:
A = [1,0,0]
B = [0,1,0]

produto= np.cross(A,B)

print(P)

[0 0 1]


In [52]:
P = np.cross(np.array([1,0,0]),np.array([0,1,0]))
print(P)


[0 0 1]


## Matrizes

In [53]:
matrix=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
print(matrix)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


## Exercício III - Matrizes

In [67]:
x = np.transpose(matrix)
print(x)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## Exercício IV

In [ ]:
matrix=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(matrix)

## Multiplicação Matriz-Vetor

In [66]:
matrix=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
vector=np.array([1,1,1,1])
print(np.dot(matrix,vector))

[10 26 42]
